# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\designer.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.groupBox_menu = QtWidgets.QGroupBox(Dialog)
        self.groupBox_menu.setGeometry(QtCore.QRect(10, 10, 1001, 71))
        self.groupBox_menu.setTitle("")
        self.groupBox_menu.setObjectName("groupBox_menu")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_menu)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_update = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_update.sizePolicy().hasHeightForWidth())
        self.btn_update.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("나눔고딕코딩")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_update.setFont(font)
        self.btn_update.setObjectName("btn_update")
        self.horizontalLayout.addWidget(self.btn_update)
        self.label_empty = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_empty.sizePolicy().hasHeightForWidth())
        self.label_empty.setSizePolicy(sizePolicy)
        self.label_empty.setText("")
        self.label_empty.setObjectName("label_empty")
        self.horizontalLayout.addWidget(self.label_empty)
        self.label_from = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_from.sizePolicy().hasHeightForWidth())
        self.label_from.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("나눔고딕코딩")
        font.setPointSize(10)
        self.label_from.setFont(font)
        self.label_from.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_from.setIndent(-1)
        self.label_from.setObjectName("label_from")
        self.horizontalLayout.addWidget(self.label_from)
        self.spinBox_from = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_from.sizePolicy().hasHeightForWidth())
        self.spinBox_from.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("나눔고딕코딩")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_from.setFont(font)
        self.spinBox_from.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_from.setMinimum(1)
        self.spinBox_from.setMaximum(1000)
        self.spinBox_from.setObjectName("spinBox_from")
        self.horizontalLayout.addWidget(self.spinBox_from)
        self.label_to = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("나눔고딕코딩")
        font.setPointSize(10)
        self.label_to.setFont(font)
        self.label_to.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_to.setIndent(-1)
        self.label_to.setObjectName("label_to")
        self.horizontalLayout.addWidget(self.label_to)
        self.spinBox_to = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_to.sizePolicy().hasHeightForWidth())
        self.spinBox_to.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("나눔고딕코딩")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_to.setFont(font)
        self.spinBox_to.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_to.setMinimum(1)
        self.spinBox_to.setMaximum(1000)
        self.spinBox_to.setObjectName("spinBox_to")
        self.horizontalLayout.addWidget(self.spinBox_to)
        self.btn_analyze = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_analyze.sizePolicy().hasHeightForWidth())
        self.btn_analyze.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("나눔고딕코딩")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_analyze.setFont(font)
        self.btn_analyze.setObjectName("btn_analyze")
        self.horizontalLayout.addWidget(self.btn_analyze)
        self.groupBox_analy_result = QtWidgets.QGroupBox(Dialog)
        self.groupBox_analy_result.setGeometry(QtCore.QRect(10, 90, 161, 661))
        font = QtGui.QFont()
        font.setFamily("나눔고딕코딩")
        font.setPointSize(10)
        self.groupBox_analy_result.setFont(font)
        self.groupBox_analy_result.setObjectName("groupBox_analy_result")
        self.tableView = QtWidgets.QTableView(self.groupBox_analy_result)
        self.tableView.setGeometry(QtCore.QRect(10, 20, 141, 631))
        font = QtGui.QFont()
        font.setFamily("나눔고딕코딩")
        font.setPointSize(10)
        self.tableView.setFont(font)
        self.tableView.setObjectName("tableView")
        self.groupBox_selec_number = QtWidgets.QGroupBox(Dialog)
        self.groupBox_selec_number.setGeometry(QtCore.QRect(180, 90, 311, 81))
        font = QtGui.QFont()
        font.setFamily("나눔고딕코딩")
        font.setPointSize(10)
        self.groupBox_selec_number.setFont(font)
        self.groupBox_selec_number.setObjectName("groupBox_selec_number")
        self.listView = QtWidgets.QListView(self.groupBox_selec_number)
        self.listView.setGeometry(QtCore.QRect(10, 20, 291, 51))
        font = QtGui.QFont()
        font.setFamily("나눔고딕코딩")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.listView.setFont(font)
        self.listView.setFlow(QtWidgets.QListView.LeftToRight)
        self.listView.setObjectName("listView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_update.setText(_translate("Dialog", "UPDATE"))
        self.label_from.setText(_translate("Dialog", "from"))
        self.label_to.setText(_translate("Dialog", "to"))
        self.btn_analyze.setText(_translate("Dialog", "ANALYZE"))
        self.groupBox_analy_result.setTitle(_translate("Dialog", "Analyzed Result"))
        self.groupBox_selec_number.setTitle(_translate("Dialog", "Selected Number"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

